#!/bin/bash

# Utility functions for project setup

# Create the project from template
create_project() {
    local project_name=$1
    local framework=$2
    local package_manager=$3

    echo -e "${BLUE}Creating $framework project: $project_name${NC}"

    if [ "$framework" = "nextjs" ]; then
        # Create Next.js project with TypeScript and Tailwind
        if [ "$package_manager" = "pnpm" ]; then
            pnpm create next-app@latest "$project_name" \
                --typescript \
                --tailwind \
                --app \
                --no-src-dir \
                --import-alias "@/*" \
                --turbopack \
                --no-git
        elif [ "$package_manager" = "yarn" ]; then
            yarn create next-app "$project_name" \
                --typescript \
                --tailwind \
                --app \
                --no-src-dir \
                --import-alias "@/*" \
                --turbopack \
                --no-git
        else
            npx create-next-app@latest "$project_name" \
                --typescript \
                --tailwind \
                --app \
                --no-src-dir \
                --import-alias "@/*" \
                --turbopack \
                --no-git
        fi
    fi

    echo -e "${GREEN}✓ Project created${NC}"
}

# Generate environment files based on selected services
generate_env_files() {
    local use_vercel=$1
    local use_convex=$2
    local use_clerk=$3
    local use_axiom=$4
    local use_linear=$5
    local use_ai=$6
    local ai_provider=$7

    # Create .env.local for development
    cat > .env.local << EOF
# ============================================
# DEVELOPMENT ENVIRONMENT VARIABLES
# ============================================
# Generated by Fullstack Project Template Generator
# Fill in the values marked with TODO

# Node Environment
NODE_ENV=development

EOF

    if $use_vercel; then
        cat >> .env.local << EOF
# --------------------------------------------
# Vercel
# --------------------------------------------
# Configured automatically via Vercel CLI
# No environment variables needed for development

EOF
    fi

    if $use_convex; then
        cat >> .env.local << EOF
# --------------------------------------------
# Convex (Backend/Database)
# --------------------------------------------
# Development deployment
NEXT_PUBLIC_CONVEX_URL=
# TODO: Copy from convex dashboard or run: npx convex dev

EOF
    fi

    if $use_clerk; then
        cat >> .env.local << EOF
# --------------------------------------------
# Clerk (Authentication)
# --------------------------------------------
# Development instance
# Get these from: https://dashboard.clerk.com
# See SETUP_GUIDE.md for detailed instructions

NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_TODO
CLERK_SECRET_KEY=sk_test_TODO

# Optional: Clerk Webhook Secret
CLERK_WEBHOOK_SECRET=whsec_TODO

# Clerk URLs (auto-configured for Next.js)
NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard

EOF
    fi

    if $use_axiom; then
        cat >> .env.local << EOF
# --------------------------------------------
# Axiom (Observability)
# --------------------------------------------
# Dataset and token configured via Axiom CLI
AXIOM_DATASET=
AXIOM_TOKEN=
# TODO: Values should be auto-filled by axiom CLI

EOF
    fi

    if $use_linear; then
        cat >> .env.local << EOF
# --------------------------------------------
# Linear (Project Management)
# --------------------------------------------
# Get API key from: https://linear.app/settings/api
# See SETUP_GUIDE.md for GraphQL setup instructions

LINEAR_API_KEY=lin_api_TODO
LINEAR_WEBHOOK_SECRET=TODO

EOF
    fi

    # Add AI provider keys
    if $use_ai; then
        cat >> .env.local << EOF
# --------------------------------------------
# AI Integration
# --------------------------------------------
EOF

        if [ "$ai_provider" = "openai" ] || [ "$ai_provider" = "both" ]; then
            cat >> .env.local << EOF
# OpenAI API Key
# Get from: https://platform.openai.com/api-keys
OPENAI_API_KEY=sk-proj-TODO

EOF
        fi

        if [ "$ai_provider" = "anthropic" ] || [ "$ai_provider" = "both" ]; then
            cat >> .env.local << EOF
# Anthropic API Key
# Get from: https://console.anthropic.com/settings/keys
ANTHROPIC_API_KEY=sk-ant-TODO

EOF
        fi
    fi

    # Add common variables
    cat >> .env.local << EOF
# --------------------------------------------
# Application Settings
# --------------------------------------------
NEXT_PUBLIC_APP_URL=http://localhost:3000

EOF

    echo -e "${GREEN}✓ .env.local created${NC}"

    # Create .env.production template
    cat > .env.production.template << EOF
# ============================================
# PRODUCTION ENVIRONMENT VARIABLES
# ============================================
# This is a template - DO NOT commit with real values
# Set these in your Vercel/hosting dashboard

# Node Environment
NODE_ENV=production

EOF

    if $use_convex; then
        cat >> .env.production.template << EOF
# Convex Production
NEXT_PUBLIC_CONVEX_URL=https://your-production.convex.cloud
CONVEX_DEPLOY_KEY=prod_TODO

EOF
    fi

    if $use_clerk; then
        cat >> .env.production.template << EOF
# Clerk Production
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_TODO
CLERK_SECRET_KEY=sk_live_TODO
CLERK_WEBHOOK_SECRET=whsec_TODO

EOF
    fi

    if $use_axiom; then
        cat >> .env.production.template << EOF
# Axiom Production
AXIOM_DATASET=your-project-prod
AXIOM_TOKEN=xaat-prod-TODO

EOF
    fi

    if $use_linear; then
        cat >> .env.production.template << EOF
# Linear Production
LINEAR_API_KEY=lin_api_TODO
LINEAR_WEBHOOK_SECRET=TODO

EOF
    fi

    # Add AI provider keys to production template
    if $use_ai; then
        cat >> .env.production.template << EOF
# AI Integration Production
EOF

        if [ "$ai_provider" = "openai" ] || [ "$ai_provider" = "both" ]; then
            cat >> .env.production.template << EOF
OPENAI_API_KEY=sk-proj-TODO

EOF
        fi

        if [ "$ai_provider" = "anthropic" ] || [ "$ai_provider" = "both" ]; then
            cat >> .env.production.template << EOF
ANTHROPIC_API_KEY=sk-ant-TODO

EOF
        fi
    fi

    cat >> .env.production.template << EOF
# Application
NEXT_PUBLIC_APP_URL=https://your-domain.com

EOF

    echo -e "${GREEN}✓ .env.production.template created${NC}"

    # Create .gitignore entry for env files
    if ! grep -q ".env.local" .gitignore 2>/dev/null; then
        cat >> .gitignore << EOF

# Environment variables
.env*.local
.env.production

EOF
        echo -e "${GREEN}✓ Updated .gitignore${NC}"
    fi
}

# Create setup guides for manual services
create_setup_guides() {
    local use_clerk=$1
    local use_linear=$2

    cat > SETUP_GUIDE.md << EOF
# Setup Guide

This guide covers manual setup for services that don't have CLI automation.

---

EOF

    if $use_clerk; then
        cat >> SETUP_GUIDE.md << EOF
## 🔐 Clerk (Authentication)

Clerk requires manual dashboard setup. Follow these steps:

### Development Environment

1. **Create Account & Application**
   - Go to: https://dashboard.clerk.com
   - Sign up or log in
   - Click "Add application"
   - Name it: \`your-project-dev\`
   - Choose authentication methods (Email, Google, GitHub, etc.)

2. **Get API Keys**
   - In your application dashboard, go to "API Keys"
   - Copy the following:
     - \`NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY\` (starts with \`pk_test_\`)
     - \`CLERK_SECRET_KEY\` (starts with \`sk_test_\`)
   - Paste them into \`.env.local\`

3. **Configure Webhook (Optional)**
   - Go to "Webhooks" in Clerk dashboard
   - Click "Add Endpoint"
   - URL: \`http://localhost:3000/api/webhooks/clerk\` (or your dev URL)
   - Subscribe to events: \`user.created\`, \`user.updated\`, \`session.created\`
   - Copy the signing secret to \`CLERK_WEBHOOK_SECRET\` in \`.env.local\`

4. **Configure URLs**
   - The template already includes correct redirect URLs
   - \`/sign-in\`, \`/sign-up\`, \`/dashboard\`

### Production Environment

1. **Create Production Application**
   - In Clerk dashboard, click "Add application"
   - Name it: \`your-project-prod\`
   - Use the same authentication methods as dev

2. **Get Production API Keys**
   - Copy \`pk_live_\` and \`sk_live_\` keys
   - Add them to Vercel environment variables (not .env file!)

3. **Production Webhook**
   - Add endpoint: \`https://your-domain.com/api/webhooks/clerk\`
   - Copy signing secret to Vercel environment variables

### Documentation
- Official Docs: https://clerk.com/docs/quickstarts/nextjs
- API Reference: https://clerk.com/docs/reference/clerk-react

---

EOF
    fi

    if $use_linear; then
        cat >> SETUP_GUIDE.md << EOF
## 📊 Linear (Project Management)

Linear uses GraphQL API. Here's how to set it up:

### Get API Access

1. **Create API Key**
   - Go to: https://linear.app/settings/api
   - Click "Personal API keys"
   - Click "Create new key"
   - Name it: \`your-project-api\`
   - Copy the key (starts with \`lin_api_\`)
   - Paste into \`.env.local\` as \`LINEAR_API_KEY\`

2. **GraphQL Endpoint**
   - API endpoint: \`https://api.linear.app/graphql\`
   - Already configured in the template

### Example Usage

\`\`\`typescript
// lib/linear.ts
const LINEAR_API_URL = 'https://api.linear.app/graphql';

async function queryLinear(query: string, variables = {}) {
  const response = await fetch(LINEAR_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': process.env.LINEAR_API_KEY!,
    },
    body: JSON.stringify({ query, variables }),
  });

  return response.json();
}

// Get all issues
const { data } = await queryLinear(\`
  query {
    issues {
      nodes {
        id
        title
        state { name }
        assignee { name }
      }
    }
  }
\`);
\`\`\`

### Common Queries

**Create Issue:**
\`\`\`graphql
mutation CreateIssue(\$teamId: String!, \$title: String!, \$description: String) {
  issueCreate(input: {
    teamId: \$teamId
    title: \$title
    description: \$description
  }) {
    success
    issue { id title }
  }
}
\`\`\`

**Get Team Issues:**
\`\`\`graphql
query TeamIssues(\$teamId: String!) {
  team(id: \$teamId) {
    issues {
      nodes {
        id
        title
        priority
        state { name }
      }
    }
  }
}
\`\`\`

### Webhooks (Optional)

1. **Create Webhook**
   - Go to team settings in Linear
   - Click "Webhooks"
   - Add endpoint: \`https://your-domain.com/api/webhooks/linear\`
   - Subscribe to events (issue created, updated, etc.)
   - Copy the secret to \`LINEAR_WEBHOOK_SECRET\`

### Documentation
- GraphQL API: https://developers.linear.app/docs/graphql/working-with-the-graphql-api
- API Reference: https://studio.apollographql.com/public/Linear-API/home
- SDK (Optional): https://github.com/linear/linear

---

EOF
    fi

    cat >> SETUP_GUIDE.md << EOF
## ✅ Verification Checklist

Before running \`npm run dev\`, make sure:

EOF

    if $use_clerk; then
        cat >> SETUP_GUIDE.md << EOF
- [ ] Clerk publishable key added to .env.local
- [ ] Clerk secret key added to .env.local
EOF
    fi

    if $use_linear; then
        cat >> SETUP_GUIDE.md << EOF
- [ ] Linear API key added to .env.local
EOF
    fi

    cat >> SETUP_GUIDE.md << EOF
- [ ] All TODO values in .env.local replaced with real values
- [ ] .env.local is in .gitignore (don't commit secrets!)

## 🚀 Ready to Code!

Once everything is configured:

\`\`\`bash
npm run dev
# or
pnpm dev
# or
yarn dev
\`\`\`

Your app should be running at: http://localhost:3000

EOF

    echo -e "${GREEN}✓ SETUP_GUIDE.md created${NC}"
}
