#!/bin/bash

# Utility functions for project setup

# Create the project from template
create_project() {
    local project_name=$1
    local framework=$2
    local package_manager=$3

    echo -e "${BLUE}Creating $framework project: $project_name${NC}"

    if [ "$framework" = "nextjs" ]; then
        # Create Next.js project with TypeScript and Tailwind
        if [ "$package_manager" = "pnpm" ]; then
            pnpm create next-app@latest "$project_name" \
                --typescript \
                --tailwind \
                --app \
                --no-src-dir \
                --import-alias "@/*" \
                --turbopack \
                --eslint \
                --no-react-compiler \
                --no-git
        elif [ "$package_manager" = "yarn" ]; then
            yarn create next-app "$project_name" \
                --typescript \
                --tailwind \
                --app \
                --no-src-dir \
                --import-alias "@/*" \
                --turbopack \
                --eslint \
                --no-react-compiler \
                --no-git
        else
            npx create-next-app@latest "$project_name" \
                --typescript \
                --tailwind \
                --app \
                --no-src-dir \
                --import-alias "@/*" \
                --turbopack \
                --eslint \
                --no-react-compiler \
                --no-git
        fi
    fi

    echo -e "${GREEN}✓ Project created${NC}"
}

# Generate environment files based on selected services
generate_env_files() {
    local use_vercel=$1
    local use_convex=$2
    local use_clerk=$3
    local use_axiom=$4
    local use_linear=$5
    local use_ai=$6
    local ai_provider=$7

    # Create .env.local for development
    cat > .env.local << EOF
# ============================================
# DEVELOPMENT ENVIRONMENT VARIABLES
# ============================================
# Generated by Launchify
# Fill in the values marked with TODO

# Node Environment
NODE_ENV=development

EOF

    if $use_vercel; then
        cat >> .env.local << EOF
# --------------------------------------------
# Vercel
# --------------------------------------------
# Configured automatically via Vercel CLI
# No environment variables needed for development

EOF
    fi

    if $use_convex; then
        cat >> .env.local << EOF
# ============================================
# CONVEX DATABASE
# ============================================
# Development/Preview Environment
NEXT_PUBLIC_CONVEX_URL=https://...convex.cloud
CONVEX_DEPLOY_KEY=dev_...
# TODO: Run 'npx convex dev' to get these values

# Production Environment (set in Vercel for main branch)
# NEXT_PUBLIC_CONVEX_URL=https://...convex.cloud
# CONVEX_DEPLOY_KEY=prod_...
# Run 'npx convex deploy --prod' to create production deployment

# Convex deployment alias for local CLI usage
CONVEX_DEPLOYMENT=dev:$PROJECT_NAME

EOF
    fi

    if $use_clerk; then
        cat >> .env.local << EOF
# ============================================
# CLERK AUTHENTICATION
# ============================================
# Development/Preview Environment
# Get these from: https://dashboard.clerk.com
# See SETUP_GUIDE.md for detailed instructions
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_TODO
CLERK_SECRET_KEY=sk_test_TODO

# Production Environment (set in Vercel for main branch)
# NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_TODO
# CLERK_SECRET_KEY=sk_live_TODO

# Clerk URLs (same across all environments)
NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard

# Optional: Clerk Webhook Secret
# CLERK_WEBHOOK_SECRET=whsec_TODO

EOF
    fi

    if $use_axiom; then
        cat >> .env.local << EOF
# ============================================
# AXIOM OBSERVABILITY
# ============================================
# Development/Preview Environment
AXIOM_DATASET=$PROJECT_NAME-dev
AXIOM_TOKEN=xaat_TODO
AXIOM_ORG_ID=TODO
# TODO: Run 'axiom auth login' and create dataset

# Production Environment (set in Vercel for main branch)
# AXIOM_DATASET=$PROJECT_NAME-prod
# Note: AXIOM_TOKEN and AXIOM_ORG_ID are same across environments

EOF
    fi

    if $use_linear; then
        cat >> .env.local << EOF
# ============================================
# LINEAR (Issue/Project Tracking)
# ============================================
# Get API key from: https://linear.app/settings/api
# See SETUP_GUIDE.md for GraphQL setup instructions
# Same key works across all environments
LINEAR_API_KEY=lin_api_TODO
LINEAR_TEAM_ID=TODO

# Optional: Webhook secret
# LINEAR_WEBHOOK_SECRET=TODO

EOF
    fi

    # Add AI provider keys
    if $use_ai; then
        cat >> .env.local << EOF
# ============================================
# AI INTEGRATION
# ============================================
# Same API keys work across all environments (usage-based billing)
EOF

        if [ "$ai_provider" = "openai" ] || [ "$ai_provider" = "both" ]; then
            cat >> .env.local << EOF
# OpenAI API
# Get from: https://platform.openai.com/api-keys
OPENAI_API_KEY=sk-proj-TODO

EOF
        fi

        if [ "$ai_provider" = "anthropic" ] || [ "$ai_provider" = "both" ]; then
            cat >> .env.local << EOF
# Anthropic API
# Get from: https://console.anthropic.com/settings/keys
ANTHROPIC_API_KEY=sk-ant-TODO

EOF
        fi
    fi

    # Add application configuration
    cat >> .env.local << EOF
# ============================================
# APPLICATION CONFIGURATION
# ============================================
NEXT_PUBLIC_APP_URL=http://localhost:3000
# Production: Set to https://your-domain.com in Vercel

# Environment indicator
NEXT_PUBLIC_ENVIRONMENT=development
# Production: NEXT_PUBLIC_ENVIRONMENT=production
# Preview: NEXT_PUBLIC_ENVIRONMENT=preview

# Data retention (days)
DATA_RETENTION_DAYS=30

# EU Region Compliance
NEXT_PUBLIC_EU_REGION=true

EOF

    echo -e "${GREEN}✓ .env.local created${NC}"

    # Create .env.production template
    cat > .env.production.template << EOF
# ============================================
# PRODUCTION ENVIRONMENT VARIABLES
# ============================================
# This is a template - DO NOT commit with real values
# Set these in your Vercel/hosting dashboard

# Node Environment
NODE_ENV=production

EOF

    if $use_convex; then
        cat >> .env.production.template << EOF
# Convex Production
NEXT_PUBLIC_CONVEX_URL=https://your-production.convex.cloud
CONVEX_DEPLOY_KEY=prod_TODO

EOF
    fi

    if $use_clerk; then
        cat >> .env.production.template << EOF
# Clerk Production
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_TODO
CLERK_SECRET_KEY=sk_live_TODO
CLERK_WEBHOOK_SECRET=whsec_TODO

EOF
    fi

    if $use_axiom; then
        cat >> .env.production.template << EOF
# Axiom Production
AXIOM_DATASET=your-project-prod
AXIOM_TOKEN=xaat-prod-TODO

EOF
    fi

    if $use_linear; then
        cat >> .env.production.template << EOF
# Linear Production
LINEAR_API_KEY=lin_api_TODO
LINEAR_WEBHOOK_SECRET=TODO

EOF
    fi

    # Add AI provider keys to production template
    if $use_ai; then
        cat >> .env.production.template << EOF
# AI Integration Production
EOF

        if [ "$ai_provider" = "openai" ] || [ "$ai_provider" = "both" ]; then
            cat >> .env.production.template << EOF
OPENAI_API_KEY=sk-proj-TODO

EOF
        fi

        if [ "$ai_provider" = "anthropic" ] || [ "$ai_provider" = "both" ]; then
            cat >> .env.production.template << EOF
ANTHROPIC_API_KEY=sk-ant-TODO

EOF
        fi
    fi

    cat >> .env.production.template << EOF
# Application
NEXT_PUBLIC_APP_URL=https://your-domain.com

EOF

    echo -e "${GREEN}✓ .env.production.template created${NC}"

    # Create .gitignore entry for env files
    if ! grep -q ".env.local" .gitignore 2>/dev/null; then
        cat >> .gitignore << EOF

# Environment variables
.env*.local
.env.production

EOF
        echo -e "${GREEN}✓ Updated .gitignore${NC}"
    fi
}

# Create setup guides for manual services
create_setup_guides() {
    local use_clerk=$1
    local use_linear=$2

    cat > SETUP_GUIDE.md << EOF
# Setup Guide

This guide covers manual setup for services that don't have CLI automation.

## 📚 Important: Vercel Environment Variables

Before setting up individual services, **read the comprehensive guide on Vercel environment variables**:

👉 **See: \`VERCEL_ENVIRONMENT_SETUP.md\`** in the project root

This explains:
- How Vercel's three environments work (Production/Preview/Development)
- Which variables to set where
- How branch-based deployments work
- Production vs development resource separation

---

EOF

    if $use_clerk; then
        cat >> SETUP_GUIDE.md << EOF
## 🔐 Clerk (Authentication)

Clerk requires manual dashboard setup. Follow these steps:

### Development Environment

1. **Create Account & Application**
   - Go to: https://dashboard.clerk.com
   - Sign up or log in
   - Click "Add application"
   - Name it: \`your-project-dev\`
   - Choose authentication methods (Email, Google, GitHub, etc.)

2. **Get API Keys**
   - In your application dashboard, go to "API Keys"
   - Copy the following:
     - \`NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY\` (starts with \`pk_test_\`)
     - \`CLERK_SECRET_KEY\` (starts with \`sk_test_\`)
   - Paste them into \`.env.local\`

3. **Configure Webhook (Optional)**
   - Go to "Webhooks" in Clerk dashboard
   - Click "Add Endpoint"
   - URL: \`http://localhost:3000/api/webhooks/clerk\` (or your dev URL)
   - Subscribe to events: \`user.created\`, \`user.updated\`, \`session.created\`
   - Copy the signing secret to \`CLERK_WEBHOOK_SECRET\` in \`.env.local\`

4. **Configure URLs**
   - The template already includes correct redirect URLs
   - \`/sign-in\`, \`/sign-up\`, \`/dashboard\`

### Production Environment

1. **Create Production Application**
   - In Clerk dashboard, click "Add application"
   - Name it: \`your-project-prod\`
   - Use the same authentication methods as dev

2. **Get Production API Keys**
   - Copy \`pk_live_\` and \`sk_live_\` keys
   - Add them to Vercel environment variables (not .env file!)

3. **Production Webhook**
   - Add endpoint: \`https://your-domain.com/api/webhooks/clerk\`
   - Copy signing secret to Vercel environment variables

### Documentation
- Official Docs: https://clerk.com/docs/quickstarts/nextjs
- API Reference: https://clerk.com/docs/reference/clerk-react

---

EOF
    fi

    if $use_linear; then
        cat >> SETUP_GUIDE.md << EOF
## 📊 Linear (Issue/Project Tracking)

Linear is an issue tracking and project management tool (like Jira). Here's how to integrate it via GraphQL API:

### Get API Access

1. **Create API Key**
   - Go to: https://linear.app/settings/api
   - Click "Personal API keys"
   - Click "Create new key"
   - Name it: \`your-project-api\`
   - Copy the key (starts with \`lin_api_\`)
   - Paste into \`.env.local\` as \`LINEAR_API_KEY\`

2. **GraphQL Endpoint**
   - API endpoint: \`https://api.linear.app/graphql\`
   - Already configured in the template

### Example Usage

\`\`\`typescript
// lib/linear.ts
const LINEAR_API_URL = 'https://api.linear.app/graphql';

async function queryLinear(query: string, variables = {}) {
  const response = await fetch(LINEAR_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': process.env.LINEAR_API_KEY!,
    },
    body: JSON.stringify({ query, variables }),
  });

  return response.json();
}

// Get all issues
const { data } = await queryLinear(\`
  query {
    issues {
      nodes {
        id
        title
        state { name }
        assignee { name }
      }
    }
  }
\`);
\`\`\`

### Common Queries

**Create Issue:**
\`\`\`graphql
mutation CreateIssue(\$teamId: String!, \$title: String!, \$description: String) {
  issueCreate(input: {
    teamId: \$teamId
    title: \$title
    description: \$description
  }) {
    success
    issue { id title }
  }
}
\`\`\`

**Get Team Issues:**
\`\`\`graphql
query TeamIssues(\$teamId: String!) {
  team(id: \$teamId) {
    issues {
      nodes {
        id
        title
        priority
        state { name }
      }
    }
  }
}
\`\`\`

### Webhooks (Optional)

1. **Create Webhook**
   - Go to team settings in Linear
   - Click "Webhooks"
   - Add endpoint: \`https://your-domain.com/api/webhooks/linear\`
   - Subscribe to events (issue created, updated, etc.)
   - Copy the secret to \`LINEAR_WEBHOOK_SECRET\`

### Documentation
- GraphQL API: https://developers.linear.app/docs/graphql/working-with-the-graphql-api
- API Reference: https://studio.apollographql.com/public/Linear-API/home
- SDK (Optional): https://github.com/linear/linear

---

EOF
    fi

    cat >> SETUP_GUIDE.md << EOF
## ✅ Verification Checklist

Before running \`npm run dev\`, make sure:

EOF

    if $use_clerk; then
        cat >> SETUP_GUIDE.md << EOF
- [ ] Clerk publishable key added to .env.local
- [ ] Clerk secret key added to .env.local
EOF
    fi

    if $use_linear; then
        cat >> SETUP_GUIDE.md << EOF
- [ ] Linear API key added to .env.local
EOF
    fi

    cat >> SETUP_GUIDE.md << EOF
- [ ] All TODO values in .env.local replaced with real values
- [ ] .env.local is in .gitignore (don't commit secrets!)

## 🚀 Ready to Code!

Once everything is configured:

\`\`\`bash
npm run dev
# or
pnpm dev
# or
yarn dev
\`\`\`

Your app should be running at: http://localhost:3000

EOF

    echo -e "${GREEN}✓ SETUP_GUIDE.md created${NC}"
}

# Show manual setup summary
show_manual_setup_summary() {
    local use_clerk=$1
    local use_axiom=$2
    local use_linear=$3
    local use_ai=$4
    local ai_provider=$5
    local clerk_automated=$6

    local needs_manual=false

    echo -e "${YELLOW}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${YELLOW}║         📋 MANUAL SETUP REQUIRED                           ║${NC}"
    echo -e "${YELLOW}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    # Check if Clerk was automated
    if $use_clerk && ! $clerk_automated; then
        needs_manual=true
        echo -e "${CYAN}🔐 Clerk Authentication${NC}"
        echo -e "   ${YELLOW}Action needed:${NC} Add API keys to .env.local"
        echo ""
        echo -e "   1. Go to ${CYAN}https://dashboard.clerk.com${NC}"
        echo -e "   2. Create a new application (Development)"
        echo -e "   3. Copy your keys from Dashboard → API Keys"
        echo -e "   4. Update .env.local with:"
        echo -e "      ${GREEN}NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY${NC}=pk_test_..."
        echo -e "      ${GREEN}CLERK_SECRET_KEY${NC}=sk_test_..."
        echo ""
        echo -e "   ${BLUE}ℹ️  See SETUP_GUIDE.md for detailed instructions${NC}"
        echo ""
    fi

    if $use_axiom; then
        needs_manual=true
        echo -e "${CYAN}🔸 Axiom Observability${NC}"
        echo -e "   ${YELLOW}Action needed:${NC} Complete dataset and token setup"
        echo ""
        echo -e "   Run these commands:"
        echo -e "   ${GREEN}axiom auth login${NC}                    # Login to Axiom"
        echo -e "   ${GREEN}axiom dataset create <name>-dev${NC}    # Create dev dataset"
        echo -e "   ${GREEN}axiom token create${NC}                 # Create API token"
        echo ""
        echo -e "   Then update .env.local with:"
        echo -e "      ${GREEN}AXIOM_DATASET${NC}=your-dataset-name"
        echo -e "      ${GREEN}AXIOM_TOKEN${NC}=xaat_..."
        echo -e "      ${GREEN}AXIOM_ORG_ID${NC}=your-org-id"
        echo ""
    fi

    if $use_linear; then
        needs_manual=true
        echo -e "${CYAN}📋 Linear Issue Tracking${NC}"
        echo -e "   ${YELLOW}Action needed:${NC} Get API key"
        echo ""
        echo -e "   1. Go to ${CYAN}https://linear.app/settings/api${NC}"
        echo -e "   2. Click 'Create new key'"
        echo -e "   3. Copy the API key"
        echo -e "   4. Update .env.local with:"
        echo -e "      ${GREEN}LINEAR_API_KEY${NC}=lin_api_..."
        echo -e "      ${GREEN}LINEAR_TEAM_ID${NC}=your-team-id"
        echo ""
        echo -e "   ${BLUE}ℹ️  See SETUP_GUIDE.md for GraphQL examples${NC}"
        echo ""
    fi

    if $use_ai; then
        needs_manual=true
        if [ "$ai_provider" = "openai" ] || [ "$ai_provider" = "both" ]; then
            echo -e "${CYAN}🤖 OpenAI API${NC}"
            echo -e "   ${YELLOW}Action needed:${NC} Get API key"
            echo ""
            echo -e "   1. Go to ${CYAN}https://platform.openai.com/api-keys${NC}"
            echo -e "   2. Click '+ Create new secret key'"
            echo -e "   3. Copy the key (starts with sk-proj-...)"
            echo -e "   4. Update .env.local with:"
            echo -e "      ${GREEN}OPENAI_API_KEY${NC}=sk-proj-..."
            echo ""
        fi

        if [ "$ai_provider" = "anthropic" ] || [ "$ai_provider" = "both" ]; then
            echo -e "${CYAN}🤖 Anthropic API (Claude)${NC}"
            echo -e "   ${YELLOW}Action needed:${NC} Get API key"
            echo ""
            echo -e "   1. Go to ${CYAN}https://console.anthropic.com/settings/keys${NC}"
            echo -e "   2. Click 'Create Key'"
            echo -e "   3. Copy the key (starts with sk-ant-...)"
            echo -e "   4. Update .env.local with:"
            echo -e "      ${GREEN}ANTHROPIC_API_KEY${NC}=sk-ant-..."
            echo ""
        fi
    fi

    if ! $needs_manual; then
        echo -e "${GREEN}✅ All services configured automatically!${NC}"
        echo -e ""
        echo -e "You can start development immediately:"
        echo -e "  ${CYAN}npm run dev${NC}"
        echo ""
    else
        echo -e "${YELLOW}╔════════════════════════════════════════════════════════════╗${NC}"
        echo -e "${YELLOW}║  ⚠️  Complete the steps above before running your app     ║${NC}"
        echo -e "${YELLOW}╚════════════════════════════════════════════════════════════╝${NC}"
        echo ""
        echo -e "${CYAN}Quick checklist:${NC}"
        echo -e "  1. ${CYAN}Open .env.local in your editor${NC}"
        echo -e "  2. ${CYAN}Find lines with 'TODO'${NC}"
        echo -e "  3. ${CYAN}Follow the links above to get your API keys${NC}"
        echo -e "  4. ${CYAN}Replace TODO values with real keys${NC}"
        echo -e "  5. ${CYAN}Save the file${NC}"
        echo -e "  6. ${CYAN}Run: npm run dev${NC}"
        echo ""
    fi

    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}📚 Documentation:${NC}"
    echo -e "  • ${CYAN}.env.local${NC} - All environment variables with inline comments"
    echo -e "  • ${CYAN}SETUP_GUIDE.md${NC} - Step-by-step setup instructions"
    echo -e "  • ${CYAN}README.md${NC} - Project overview and usage"
    if [ -f "VERCEL_ENVIRONMENT_SETUP.md" ]; then
        echo -e "  • ${CYAN}VERCEL_ENVIRONMENT_SETUP.md${NC} - Production deployment guide"
    fi
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}
